name: torch_dart
description: Backend-independent Dart bindings for PyTorch.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.13.0

resolution: workspace

dependencies:
  meta: ^1.19.0
  py_embed: ^0.4.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
