// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

@ffi.Native<
  ffi.Pointer<PyObject> Function(ffi.Pointer<PyObject>, ffi.Pointer<ffi.Char>)
>()
external ffi.Pointer<PyObject> PyObject_GetAttrString(
  ffi.Pointer<PyObject> arg0,
  ffi.Pointer<ffi.Char> arg1,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<PyObject>)>()
external void Py_IncRef(ffi.Pointer<PyObject> arg0);

@ffi.Native<ffi.Void Function(ffi.Pointer<PyObject>)>()
external void Py_DecRef(ffi.Pointer<PyObject> arg0);

@ffi.Native<ffi.Pointer<PyObject> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<PyObject> PyUnicode_FromString(ffi.Pointer<ffi.Char> u);

@ffi.Native<ffi.Pointer<PyObject> Function(ffi.LongLong)>()
external ffi.Pointer<PyObject> PyTuple_New(int size);

@ffi.Native<ffi.LongLong Function(ffi.Pointer<PyObject>)>()
external int PyTuple_Size(ffi.Pointer<PyObject> arg0);

@ffi.Native<
  ffi.Pointer<PyObject> Function(ffi.Pointer<PyObject>, ffi.LongLong)
>()
external ffi.Pointer<PyObject> PyTuple_GetItem(
  ffi.Pointer<PyObject> arg0,
  int arg1,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<PyObject>, ffi.LongLong, ffi.Pointer<PyObject>)
>()
external int PyTuple_SetItem(
  ffi.Pointer<PyObject> arg0,
  int arg1,
  ffi.Pointer<PyObject> arg2,
);

@ffi.Native<
  ffi.Pointer<PyObject> Function(
    ffi.Pointer<PyObject>,
    ffi.LongLong,
    ffi.LongLong,
  )
>()
external ffi.Pointer<PyObject> PyTuple_GetSlice(
  ffi.Pointer<PyObject> arg0,
  int arg1,
  int arg2,
);

@ffi.Native<ffi.Int Function(PyStatus)>()
external int PyStatus_Exception(PyStatus err);

@ffi.Native<ffi.Void Function(ffi.Pointer<PyConfig>)>()
external void PyConfig_InitPythonConfig(ffi.Pointer<PyConfig> config);

@ffi.Native<ffi.Void Function(ffi.Pointer<PyConfig>)>()
external void PyConfig_Clear(ffi.Pointer<PyConfig> arg0);

@ffi.Native<
  PyStatus Function(
    ffi.Pointer<PyConfig>,
    ffi.Pointer<ffi.Pointer<ffi.WChar>>,
    ffi.Pointer<ffi.WChar>,
  )
>()
external PyStatus PyConfig_SetString(
  ffi.Pointer<PyConfig> config,
  ffi.Pointer<ffi.Pointer<ffi.WChar>> config_str,
  ffi.Pointer<ffi.WChar> str,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>)>()
external int PyRun_SimpleString(ffi.Pointer<ffi.Char> s);

@ffi.Native<ffi.Void Function()>()
external void Py_Initialize();

@ffi.Native<ffi.Void Function()>()
external void Py_Finalize();

@ffi.Native<PyStatus Function(ffi.Pointer<PyConfig>)>()
external PyStatus Py_InitializeFromConfig(ffi.Pointer<PyConfig> config);

@ffi.Native<ffi.Void Function(PyStatus)>()
external void Py_ExitStatusException(PyStatus err);

@ffi.Native<ffi.Pointer<PyObject> Function(ffi.Pointer<PyObject>)>()
external ffi.Pointer<PyObject> PyImport_Import(ffi.Pointer<PyObject> name);

@ffi.Native<
  ffi.Pointer<PyObject> Function(ffi.Pointer<PyObject>, ffi.Pointer<PyObject>)
>()
external ffi.Pointer<PyObject> PyObject_CallObject(
  ffi.Pointer<PyObject> callable,
  ffi.Pointer<PyObject> args,
);

@ffi.Native<
  ffi.Pointer<PyObject> Function(
    ffi.Pointer<PyObject>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
  )
>()
external ffi.Pointer<PyObject> PyObject_CallMethod(
  ffi.Pointer<PyObject> obj,
  ffi.Pointer<ffi.Char> name,
  ffi.Pointer<ffi.Char> format,
);

final class _object extends ffi.Opaque {}

typedef PyObject = _object;

final class PyMethodDef extends ffi.Struct {
  external ffi.Pointer<ffi.Char> ml_name;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<PyObject> Function(
        ffi.Pointer<PyObject>,
        ffi.Pointer<PyObject>,
      )
    >
  >
  ml_meth;

  @ffi.Int()
  external int ml_flags;

  external ffi.Pointer<ffi.Char> ml_doc;
}

final class PyStatus extends ffi.Struct {
  @ffi.UnsignedInt()
  external int _type;

  external ffi.Pointer<ffi.Char> func;

  external ffi.Pointer<ffi.Char> err_msg;

  @ffi.Int()
  external int exitcode;
}

final class PyWideStringList extends ffi.Struct {
  @ffi.LongLong()
  external int length;

  external ffi.Pointer<ffi.Pointer<ffi.WChar>> items;
}

final class PyConfig extends ffi.Struct {
  @ffi.Int()
  external int _config_init;

  @ffi.Int()
  external int isolated;

  @ffi.Int()
  external int use_environment;

  @ffi.Int()
  external int dev_mode;

  @ffi.Int()
  external int install_signal_handlers;

  @ffi.Int()
  external int use_hash_seed;

  @ffi.UnsignedLong()
  external int hash_seed;

  @ffi.Int()
  external int faulthandler;

  @ffi.Int()
  external int tracemalloc;

  @ffi.Int()
  external int import_time;

  @ffi.Int()
  external int show_ref_count;

  @ffi.Int()
  external int show_alloc_count;

  @ffi.Int()
  external int dump_refs;

  @ffi.Int()
  external int malloc_stats;

  external ffi.Pointer<ffi.WChar> filesystem_encoding;

  external ffi.Pointer<ffi.WChar> filesystem_errors;

  external ffi.Pointer<ffi.WChar> pycache_prefix;

  @ffi.Int()
  external int parse_argv;

  external PyWideStringList argv;

  external ffi.Pointer<ffi.WChar> program_name;

  external PyWideStringList xoptions;

  external PyWideStringList warnoptions;

  @ffi.Int()
  external int site_import;

  @ffi.Int()
  external int bytes_warning;

  @ffi.Int()
  external int inspect;

  @ffi.Int()
  external int interactive;

  @ffi.Int()
  external int optimization_level;

  @ffi.Int()
  external int parser_debug;

  @ffi.Int()
  external int write_bytecode;

  @ffi.Int()
  external int verbose;

  @ffi.Int()
  external int quiet;

  @ffi.Int()
  external int user_site_directory;

  @ffi.Int()
  external int configure_c_stdio;

  @ffi.Int()
  external int buffered_stdio;

  external ffi.Pointer<ffi.WChar> stdio_encoding;

  external ffi.Pointer<ffi.WChar> stdio_errors;

  @ffi.Int()
  external int legacy_windows_stdio;

  external ffi.Pointer<ffi.WChar> check_hash_pycs_mode;

  @ffi.Int()
  external int pathconfig_warnings;

  external ffi.Pointer<ffi.WChar> pythonpath_env;

  external ffi.Pointer<ffi.WChar> home;

  @ffi.Int()
  external int module_search_paths_set;

  external PyWideStringList module_search_paths;

  external ffi.Pointer<ffi.WChar> executable;

  external ffi.Pointer<ffi.WChar> base_executable;

  external ffi.Pointer<ffi.WChar> prefix;

  external ffi.Pointer<ffi.WChar> base_prefix;

  external ffi.Pointer<ffi.WChar> exec_prefix;

  external ffi.Pointer<ffi.WChar> base_exec_prefix;

  @ffi.Int()
  external int skip_source_first_line;

  external ffi.Pointer<ffi.WChar> run_command;

  external ffi.Pointer<ffi.WChar> run_module;

  external ffi.Pointer<ffi.WChar> run_filename;

  @ffi.Int()
  external int _install_importlib;

  @ffi.Int()
  external int _init_main;
}
